class FootballNews {
  String image;
  String title;
  String date;
  String time;
  String contributor;
  String content;
  
  FootballNews({
    required this.image,
    required this.title,
    required this.date,
    required this.time,
    required this.contributor,
    required this.content
  });
}

var footballNewsList = [
  FootballNews(image: 'images/persija.jpg', title: 'Persija Datangkan Pemain Jelang Musim Baru', date: '25 September 2024', time: '03.00 WIB', contributor: 'Football News App', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id efficitur ipsum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue, libero sit amet auctor congue, leo diam imperdiet nisi, at iaculis sapien massa at odio. Fusce nibh augue, pellentesque malesuada urna facilisis, commodo congue felis. Vestibulum tellus massa, aliquet non quam et, efficitur malesuada ligula. Duis convallis arcu gravida odio vestibulum tincidunt. Curabitur condimentum sed arcu in placerat. Aenean maximus mattis urna in laoreet. Donec interdum leo eget sapien faucibus fermentum. Praesent laoreet mattis laoreet. Maecenas non quam sit amet lectus rhoncus vehicula. Nulla rhoncus et diam dignissim imperdiet. Nunc mollis nec enim non tempor. Duis placerat sit amet purus vel varius. Proin consequat augue sit amet metus mollis, quis efficitur risus sodales. Phasellus vitae diam vulputate, iaculis risus vitae, faucibus leo. In quis risus commodo, sagittis metus sed, scelerisque mauris. Vestibulum at nulla vel ex sodales tempus eu non metus. Duis varius nisi ac tellus tincidunt cursus. Suspendisse auctor vestibulum diam, ac interdum leo viverra nec. In sagittis facilisis congue. Vivamus vel augue non est interdum ultrices bibendum non ipsum. Sed vel massa at odio porttitor ornare id non nunc. Nam in erat rutrum, ultricies orci non, fringilla dolor.'),
  FootballNews(image: 'images/mancity.jpg', title: 'Man. City Melaju Ke Putaran Ketiga Piala Liga', date: '25 September 2024', time: '03.30 WIB', contributor: 'Football News App', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id efficitur ipsum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue, libero sit amet auctor congue, leo diam imperdiet nisi, at iaculis sapien massa at odio. Fusce nibh augue, pellentesque malesuada urna facilisis, commodo congue felis. Vestibulum tellus massa, aliquet non quam et, efficitur malesuada ligula. Duis convallis arcu gravida odio vestibulum tincidunt. Curabitur condimentum sed arcu in placerat. Aenean maximus mattis urna in laoreet. Donec interdum leo eget sapien faucibus fermentum. Praesent laoreet mattis laoreet. Maecenas non quam sit amet lectus rhoncus vehicula. Nulla rhoncus et diam dignissim imperdiet. Nunc mollis nec enim non tempor. Duis placerat sit amet purus vel varius. Proin consequat augue sit amet metus mollis, quis efficitur risus sodales. Phasellus vitae diam vulputate, iaculis risus vitae, faucibus leo. In quis risus commodo, sagittis metus sed, scelerisque mauris. Vestibulum at nulla vel ex sodales tempus eu non metus. Duis varius nisi ac tellus tincidunt cursus. Suspendisse auctor vestibulum diam, ac interdum leo viverra nec. In sagittis facilisis congue. Vivamus vel augue non est interdum ultrices bibendum non ipsum. Sed vel massa at odio porttitor ornare id non nunc. Nam in erat rutrum, ultricies orci non, fringilla dolor.'),
  FootballNews(image: 'images/sugbk.jpg', title: 'SUGBK Disterilkan Jelang Kualifikasi Piala Dunia 2026', date: '25 September 2024', time: '04.00 WIB', contributor: 'Football News App', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id efficitur ipsum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue, libero sit amet auctor congue, leo diam imperdiet nisi, at iaculis sapien massa at odio. Fusce nibh augue, pellentesque malesuada urna facilisis, commodo congue felis. Vestibulum tellus massa, aliquet non quam et, efficitur malesuada ligula. Duis convallis arcu gravida odio vestibulum tincidunt. Curabitur condimentum sed arcu in placerat. Aenean maximus mattis urna in laoreet. Donec interdum leo eget sapien faucibus fermentum. Praesent laoreet mattis laoreet. Maecenas non quam sit amet lectus rhoncus vehicula. Nulla rhoncus et diam dignissim imperdiet. Nunc mollis nec enim non tempor. Duis placerat sit amet purus vel varius. Proin consequat augue sit amet metus mollis, quis efficitur risus sodales. Phasellus vitae diam vulputate, iaculis risus vitae, faucibus leo. In quis risus commodo, sagittis metus sed, scelerisque mauris. Vestibulum at nulla vel ex sodales tempus eu non metus. Duis varius nisi ac tellus tincidunt cursus. Suspendisse auctor vestibulum diam, ac interdum leo viverra nec. In sagittis facilisis congue. Vivamus vel augue non est interdum ultrices bibendum non ipsum. Sed vel massa at odio porttitor ornare id non nunc. Nam in erat rutrum, ultricies orci non, fringilla dolor.'),
  FootballNews(image: 'images/spurs.jpg', title: 'Tottenham Siap Gelar Laga Kandang Di Stadion Baru', date: '25 September 2024', time: '04.30 WIB', contributor: 'Football News App', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id efficitur ipsum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue, libero sit amet auctor congue, leo diam imperdiet nisi, at iaculis sapien massa at odio. Fusce nibh augue, pellentesque malesuada urna facilisis, commodo congue felis. Vestibulum tellus massa, aliquet non quam et, efficitur malesuada ligula. Duis convallis arcu gravida odio vestibulum tincidunt. Curabitur condimentum sed arcu in placerat. Aenean maximus mattis urna in laoreet. Donec interdum leo eget sapien faucibus fermentum. Praesent laoreet mattis laoreet. Maecenas non quam sit amet lectus rhoncus vehicula. Nulla rhoncus et diam dignissim imperdiet. Nunc mollis nec enim non tempor. Duis placerat sit amet purus vel varius. Proin consequat augue sit amet metus mollis, quis efficitur risus sodales. Phasellus vitae diam vulputate, iaculis risus vitae, faucibus leo. In quis risus commodo, sagittis metus sed, scelerisque mauris. Vestibulum at nulla vel ex sodales tempus eu non metus. Duis varius nisi ac tellus tincidunt cursus. Suspendisse auctor vestibulum diam, ac interdum leo viverra nec. In sagittis facilisis congue. Vivamus vel augue non est interdum ultrices bibendum non ipsum. Sed vel massa at odio porttitor ornare id non nunc. Nam in erat rutrum, ultricies orci non, fringilla dolor.'),
  FootballNews(image: 'images/wembley.jpg', title: 'Wembley Gelar Laga Final UEFA EURO 2028', date: '25 September 2024', time: '05.00 WIB', contributor: 'Football News App', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id efficitur ipsum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue, libero sit amet auctor congue, leo diam imperdiet nisi, at iaculis sapien massa at odio. Fusce nibh augue, pellentesque malesuada urna facilisis, commodo congue felis. Vestibulum tellus massa, aliquet non quam et, efficitur malesuada ligula. Duis convallis arcu gravida odio vestibulum tincidunt. Curabitur condimentum sed arcu in placerat. Aenean maximus mattis urna in laoreet. Donec interdum leo eget sapien faucibus fermentum. Praesent laoreet mattis laoreet. Maecenas non quam sit amet lectus rhoncus vehicula. Nulla rhoncus et diam dignissim imperdiet. Nunc mollis nec enim non tempor. Duis placerat sit amet purus vel varius. Proin consequat augue sit amet metus mollis, quis efficitur risus sodales. Phasellus vitae diam vulputate, iaculis risus vitae, faucibus leo. In quis risus commodo, sagittis metus sed, scelerisque mauris. Vestibulum at nulla vel ex sodales tempus eu non metus. Duis varius nisi ac tellus tincidunt cursus. Suspendisse auctor vestibulum diam, ac interdum leo viverra nec. In sagittis facilisis congue. Vivamus vel augue non est interdum ultrices bibendum non ipsum. Sed vel massa at odio porttitor ornare id non nunc. Nam in erat rutrum, ultricies orci non, fringilla dolor.'),
];